from datetime import date, timedelta

BRANCHES = [
    (5,  "Tirunelveli-1",   "ChIJ2RU2NvQRBDsRq-Fw7IVwx7k"),
    (6,  "Tuticorin-1",     "ChIJ5zJNoJfvAzsR-bJE_3bbNYw"),
    (7,  "Thenkasi",        "ChIJuaqqquEpBDsRVITw0MMYklc"),
    (8,  "Tuticorin-2",     "ChIJH6gY4-PvAzsRJ50skTlx3cs"),
    (9,  "Thenkasi-2",      "ChIJiwqLye6DBjsRo9v1mWXaycI"),
    (10, "Ramnad",          "ChIJNVVVVaGiATsRnunSgOTvbE8"),
    (11, "Nagercoil",       "ChIJe1LZBiTxBDsRJFLjlbgZoIs"),
    (12, "Rajapalayam",     "ChIJW2ot-NDpBjsRMTfMF2IV-xE"),
    (13, "Thiruchendur-1",  "ChIJeXA4vJKRAzsRBovAtv6lMuQ"),
    (14, "Virudhunagar-2",  "ChIJPezaX7wtATsR9sHhFOG6A1c"),
    (15, "Aruppukottai",    "ChIJy6qqqgYwATsRbcp-hXnoruM"),
    (16, "Surandai-1",      "ChIJPb1_eEOdBjsRjL9IVCVJhi8"),
    (17, "Kovilpatti",      "ChIJHY0o-26yBjsRt7wbXB1pDUE"),
    (18, "Puliyankudi-1",   "ChIJjZqoc46RBjsRQTGHnNC8xxA"),
    (19, "Udankudi",        "ChIJPQAAACyEAzsRgjznQ1GLom0"),
    (20, "Aruppukottai -2", "ChIJY04wY58xATsRuoJSichVQQE"),
    (21, "Sivakasi",        "ChIJI2JvEePOBjsREh8b-x4WF4U"),
    (22, "Kulasekharam-1",  "ChIJw0Ep-kNXBDsRe5ad32jAeAk"),
    (23, "Sattur-2",        "ChIJNVVVVcHKBjsR7xMX97RFn8Q"),
    (24, "Ambasamudram-1",  "ChIJ9SGeIi85BDsRZk4QdyW9BSY"),
    (25, "Anjugramam-1",    "ChIJ4yeJebLtBDsRDceoxujdGyc"),
    (26, "Eral-2",          "ChIJbwAA0KGMAzsRkQilW5PceeA"),
    (27, "Kayathar-1",      "ChIJx5ebtUgRBDsRMquPZNUJVpw"),
    (28, "Virudhunagar",    "ChIJN3jzNJgsATsRCU3nrB5ntKE"),
    (29, "Thuckalay-1",     "ChIJc9QgEub4BDsRoyDR4Wd6tYA"),
    (30, "Sayalkudi-1",     "ChIJRTqudn9lATsR2fYyMmxlOrw"),
    (31, "Valliyur-1",      "ChIJcVNk6TtnBDsRBoP4zpExt5k"),
    (32, "Marthandam",      "ChIJcWptCRdVBDsRlJh2q0-rnfY"),
    (33, "Sengottai-1",     "ChIJw3zzKiaBBjsR9KDyGpn1nXU"),
    (34, "Karungal-1",      "ChIJfTP5ASr_BDsRgsBaeQltkw4"),
    (35, "Colachel-1",      "ChIJgRkBLw39BDsR58D0lwNo5Ts"),
    (36, "Sankarankovil-1", "ChIJE1mKnhSXBjsRKMQ-9JKQf_c"),
    (37, "Thisayanvilai-1", "ChIJVWkvdfh_BDsRdvtimKCLS5Y"),
    (38, "Paramakudi",      "ChIJ-dgjBzQHATsRf27FWAJgmsA"),
    (39, "Monday Market",   "ChIJTceRGAD5BDsR65i3YNTcYHk"),
    (40, "Villathikullam",  "ChIJi_wAkwVbATsRtFl3_V5rGrY"),
]

AGM_MAP = {
    "Tirunelveli-1": "John",    "Valliyur-1": "John",
    "Ambasamudram-1": "John",    "Anjugramam-1": "John",
    "Tuticorin-1": "Siva",      "Tuticorin-2": "Siva",
    "Thiruchendur-1": "Siva",   "Eral-2": "Siva",
    "Udankudi": "Siva",          "Thisayanvilai-1": "Siva",
    "Nagercoil": "Jeeva",       "Marthandam": "Jeeva",
    "Thuckalay-1": "Jeeva",     "Kulasekharam-1": "Jeeva",
    "Monday Market": "Jeeva",   "Karungal-1": "Jeeva",
    "Kovilpatti": "Seenivasan", "Ramnad": "Seenivasan",
    "Paramakudi": "Seenivasan", "Sayalkudi-1": "Seenivasan",
    "Villathikullam": "Seenivasan", "Sattur-2": "Seenivasan",
    "Sankarankovil-1": "Seenivasan", "Kayathar-1": "Seenivasan",
    "Thenkasi": "Muthuselvam",  "Thenkasi-2": "Muthuselvam",
    "Surandai-1": "Muthuselvam","Puliyankudi-1": "Muthuselvam",
    "Sengottai-1": "Muthuselvam","Rajapalayam": "Muthuselvam",
    "Virudhunagar": "Venkatesh","Virudhunagar-2": "Venkatesh",
    "Aruppukottai": "Venkatesh","Aruppukottai -2": "Venkatesh",
    "Sivakasi": "Venkatesh",    "Colachel-1": "Venkatesh",
}

# Build a quick lookup dict: place_id -> (branch_id, branch_name)
PLACE_ID_MAP = {place_id: (bid, name) for bid, name, place_id in BRANCHES}
